=== N0750199/eclipse.pde.incubator/presentations/extended/org.eclipse.browser/data/project_links.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

   <xs:annotation>
      <xs:documentation xml:lang="en">
         Schema for specifying project and component link hierarchies
      </xs:documentation>
   </xs:annotation>

   <!-- Attributes ///////////////////////////////////////////////////////// -->

   <xs:attributeGroup name="link_attributes">
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="link" use="required"/>
      <xs:attribute ref="description" use="required"/>
   </xs:attributeGroup>

   <xs:attribute 
      name="name" 
      type="xs:normalizedString">
      <xs:annotation>
         <xs:documentation xml:lang="en">
            Attribute for specifying the project or component name
         </xs:documentation>
      </xs:annotation>
   </xs:attribute>

   <xs:attribute 
      name="link" 
      type="xs:anyURI">
      <xs:annotation>
         <xs:documentation xml:lang="en">
            Attribute for specifying the URI to a project or component web site
         </xs:documentation>
      </xs:annotation>
   </xs:attribute>

   <xs:attribute 
      name="description" 
      type="xs:normalizedString">
      <xs:annotation>
         <xs:documentation xml:lang="en">
            Attribute for specifying the project or component description
         </xs:documentation>
      </xs:annotation>
   </xs:attribute>

   <!-- Elements /////////////////////////////////////////////////////////// -->

   <xs:element 
      name="link_element" 
      abstract="true"/>

   <xs:element 
      name="project"
      substitutionGroup="link_element">
      <xs:annotation>
         <xs:documentation xml:lang="en">
            Element for specifying a project containing one or more sub-projects
         </xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="subproject" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attributeGroup ref="link_attributes"/>
      </xs:complexType>
   </xs:element>

   <xs:element 
      name="subproject"
      substitutionGroup="link_element">
      <xs:annotation>
         <xs:documentation xml:lang="en">
            Element for specifying a sub-project containing one or more 
            sub-projects or components
         </xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="subproject" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="component" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attributeGroup ref="link_attributes"/>
      </xs:complexType>
   </xs:element>

   <xs:element 
      name="component"
      substitutionGroup="link_element">
      <xs:annotation>
         <xs:documentation xml:lang="en">
            Element for specifying a component containing one or more components
         </xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="component" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attributeGroup ref="link_attributes"/>
      </xs:complexType>
   </xs:element>

</xs:schema>

=== N0750199/eclipse.pde.incubator/presentations/eclipse-con/2007/plugins/org.eclipsecon.browser/data/eclipse_project_links.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Link -->	  
<project 
   name="Eclipse Project" 
   link="http://www.eclipse.org/eclipse/"
   description="Open source industry platform for the development of highly integrated tools."
   xsi:noNamespaceSchemaLocation="project_links.xsd"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

   <!-- Link -->	
   <subproject 
      name="Platform" 
      link="http://www.eclipse.org/platform/"
      description="Set of frameworks and common services.">

      <!-- Link -->		
      <component 
         name="Ant" 
         link="http://dev.eclipse.org/viewcvs/index.cgi/platform-ant-home/main.html?view=co"
         description="Platform Ant integration.">
      </component>		
   		
      <!-- Link -->		
      <component 
         name="Core" 
         link="http://www.eclipse.org/eclipse/platform-core/"
         description="Platform runtime and resource management.">
      </component>	

      <!-- Link -->		
      <component 
         name="CVS" 
         link="http://www.eclipse.org/eclipse/platform-cvs/"
         description="Platform CVS Integration.">
      </component>	
      
      <!-- Link -->		
      <component 
         name="Debug" 
         link="http://www.eclipse.org/eclipse/debug/index.php"
         description="Generic execution debug framework.">
      </component>	

      <!-- Link -->		
      <component 
         name="Releng" 
         link="http://www.eclipse.org/eclipse/platform-releng/index.html"
         description="Release Engineering.">
      </component>	

      <!-- Link -->		
      <component 
         name="Search" 
         link="http://www.eclipse.org/eclipse/platform-search/"
         description="Integrated search facility.">
      </component>	

      <!-- Link -->		
      <component 
         name="SWT" 
         link="http://www.eclipse.org/swt/"
         description="Standard Widget Toolkit.">
      </component>	

      <!-- Link -->		
      <component 
         name="Team/Compare" 
         link="http://www.eclipse.org/eclipse/platform-team/"
         description="Generic team and compare support frameworks.">
      </component>	

      <!-- Link -->		
      <component 
         name="Text" 
         link="http://www.eclipse.org/eclipse/platform-text/"
         description="Text editor framework.">
      </component>	

      <!-- Link -->		
      <component 
         name="User Assistance" 
         link="http://www.eclipse.org/eclipse/platform-ua/main.html"
         description="Help system, initial user experience, cheat sheets.">
      </component>	

      <!-- Link -->		
      <component 
         name="UI" 
         link="http://dev.eclipse.org/viewcvs/index.cgi/platform-ui-home/main.html?view=co"
         description="Platform user interface.">
      </component>	

      <!-- Link -->		
      <component 
         name="Update" 
         link="http://dev.eclipse.org/viewcvs/index.cgi/platform-update-home/main.html?view=co"
         description="Dynamic update, install, and field service.">
      </component>	

      <!-- Link -->		
      <component 
         name="WebDAV" 
         link="http://dev.eclipse.org/viewcvs/index.cgi/platform-webdav-home/main.html?view=co"
         description="WebDAV integration.">
      </component>	
      
   </subproject>		

   <!-- Link -->		
   <subproject 
      name="Equinox" 
      link="http://www.eclipse.org/equinox/"
      description="An OSGi framework for Eclipse.">
   </subproject>	
   
   <!-- Link -->		
   <subproject 
      name="JDT" 
      link="http://www.eclipse.org/jdt/"
      description="Java Development Tools.">

      <!-- Link -->		
      <component 
         name="APT" 
         link="http://www.eclipse.org/jdt/apt/index.html"
         description="Java 5.0 annotation processing infrastructure.">
      </component>

      <!-- Link -->		
      <component 
         name="Core" 
         link="http://www.eclipse.org/jdt/core/index.php"
         description="Java IDE headless infrastructure.">
      </component>

      <!-- Link -->		
      <component 
         name="Debug" 
         link="http://www.eclipse.org/eclipse/debug/index.php"
         description="Debug support for Java.">
      </component>

      <!-- Link -->		
      <component 
         name="UI" 
         link="http://www.eclipse.org/jdt/ui/index.php "
         description="Java IDE user interface.">
      </component>                  
   
   </subproject>	

   <!-- Link -->		
   <subproject 
      name="PDE" 
      link="http://www.eclipse.org/pde/"
      description="Plug-in development environment.">

      <!-- Link -->		
      <component 
         name="Build" 
         link="http://www.eclipse.org/pde/pde-build/"
         description="PDE build.">
      </component>

      <!-- Link -->		
      <component 
         name="UI" 
         link="http://www.eclipse.org/pde/pde-ui/"
         description="PDE user interface.">
      </component>
   
   </subproject>	      

</project>
